export const firstNames = [
    'Borticle',
    'Pickleman',
    'Bungholemius',
    'Boofenacious',
    'Barfimillius',
    'Bonkjelly',
    'Bacterial',
    'Bowserlicious',
    'Brandynugget',
    'Berillium',
    'Bendandsnap',
    'Breadbunter',
    'Benedict',
    'Blathers',
    'Basketball',
    'Brundlefly',
    'Blashpemous',
    'Bronelius',
    'Quackmuncher',
    'Bucketwrench',
    'Brøtherhamper',
    'Bansheesweat',
    'Battlestar',
    'Borkenator',
    'Bromeister',
    'Boomtastic',
    'Bignacious D.'
];

export const lastNames = [
    'Crotchetygoop',
    'Quack III Esq',
    'Crucialpants',
    'Crumbtananatch',
    'Cucumbermelon',
    'Corderoy',
    'Clementine',
    'Crackity-Jones',
    'Codswallop',
    'Crustaceous',
    'Capitalism',
    'Craftfloop',
    'California',
    'Cloptastic',
    'Cumberbatch',
    'Choochootrain',
    'Clowntickler',
    'Cahootsman',
    'Crabapple',
    'Chinchillasplash',
    'Chestershire',
    'Cerulean',
    'Chippendale',
    'Clappenator 3000',
    'Camembert'
];
